name: CI

on: [push]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install --jobs 4 --retry 3 --path vendor/bundle
      - run: bundle exec jekyll build
